import { EventNode } from "@/types/EventGraph";

export const sampleEvents: EventNode[] = [
  {
    title: "Bloc Party",
    description: "Indie rock concert",
    tags: ["indie rock concert", "indie rock"],
    date: "May 31, 2025",
    venue: "Forest Hills Stadium",
    neighborhood: "Queens, NYC",
    category: "indie rock concert",
    id: "bloc-party",
  },
  {
    title: "Halsey",
    description: "Indie pop concert",
    tags: ["indie rock concert", "indie pop"],
    date: "June 1, 2025",
    venue: "Northwell Health at Jones Beach Theater",
    neighborhood: "Wantagh, NY",
    category: "indie rock concert",
    id: "halsey",
  },
  {
    title: "Tennis",
    description: "Indie rock concert",
    tags: ["indie rock concert", "indie rock"],
    date: "June 1, 2025",
    venue: "The Rooftop at Pier 17",
    neighborhood: "New York (NYC)",
    category: "indie rock concert",
    id: "tennis",
  },
  {
    title: "The Kooks",
    description: "Indie rock concert",
    tags: ["indie rock concert", "indie rock"],
    date: "June 3, 2025",
    venue: "The Rooftop at Pier 17",
    neighborhood: "New York (NYC)",
    category: "indie rock concert",
    id: "the-kooks",
  },
  {
    title: "Craig Finn",
    description: "Indie rock concert",
    tags: ["indie rock concert", "indie rock"],
    date: "TBD",
    venue: "Rough Trade Below",
    neighborhood: "New York (NYC)",
    category: "indie rock concert",
    id: "craig-finn",
  },
  {
    title:
      "Brooklyn Chop House Summer Rooftop - Curtis Quow Exclusive Book Signing",
    description:
      "A networking event featuring Curtis Quow's exclusive book signing at Brooklyn Chop House Steakhouse in Times Square.",
    tags: ["networking event", "networking", "book signing", "rooftop"],
    url: "https://www.eventbrite.com/e/brooklyn-chop-house-summer-rooftop-curtis-quow-exclusive-book-signing-tickets-123456789",
    date: "2025-06-10",
    venue: "Brooklyn Chop House Steakhouse",
    neighborhood: "Times Square",
    keywords: ["Brooklyn Chop House", "Curtis Quow", "book signing", "rooftop"],
    category: "networking event",
    id: "brooklyn-chop-house-summer-rooftop---curtis-quow-exclusive-book-signing",
  },
  {
    title: "The Jazba Collective NYC Meetup!",
    description:
      "A networking meetup hosted by The Jazba Collective at fontainhas + (/du.kaan/) in New York City, perfect for community building and professional connections.",
    tags: ["networking event", "networking", "meetup", "community"],
    url: "https://www.eventbrite.com/e/the-jazba-collective-nyc-meetup-tickets-987654321",
    date: "2025-06-26",
    venue: "fontainhas + (/du.kaan/)",
    neighborhood: "New York City",
    keywords: ["Jazba Collective", "meetup", "networking"],
    category: "networking event",
    id: "the-jazba-collective-nyc-meetup",
  },
  {
    title: "Startup CPG Founder Dinner @ Summer Fancy Food 2025",
    description:
      "An exclusive networking dinner for startup CPG founders during the Summer Fancy Food event at Maxwell Tribeca.",
    tags: ["networking event", "networking", "startup", "dinner"],
    url: "https://www.eventbrite.com/e/startup-cpg-founder-dinner-summer-fancy-food-2025-tickets-1122334455",
    date: "2025-06-30",
    venue: "Maxwell Tribeca",
    neighborhood: "Tribeca",
    keywords: [
      "Startup CPG",
      "founder dinner",
      "Summer Fancy Food",
      "networking",
    ],
    category: "networking event",
    id: "startup-cpg-founder-dinner--summer-fancy-food-2025",
  },
  {
    title: "New York City Hottest Networking Event For Young Professionals",
    description:
      "A popular networking event aimed at young professionals in New York City, held at The Ivory Peacock.",
    tags: ["networking event", "networking", "young professionals", "social"],
    url: "https://www.eventbrite.com/e/new-york-city-hottest-networking-event-for-young-professionals-tickets-5566778899",
    date: "2025-06-11",
    venue: "The Ivory Peacock",
    neighborhood: "New York City",
    keywords: ["young professionals", "networking", "social event"],
    category: "networking event",
    id: "new-york-city-hottest-networking-event-for-young-professionals",
  },
  {
    title: "Small Business Expo NYC 2025",
    description:
      "The largest small business networking event in NYC at the Javits Center, featuring workshops, speed networking, vendors, and educational sessions for entrepreneurs and small business owners.",
    tags: [
      "networking event",
      "networking",
      "small business",
      "expo",
      "workshops",
    ],
    url: "https://www.thesmallbusinessexpo.com/city/new-york-city/",
    date: "2025-06-07",
    venue: "Javits Convention Center",
    neighborhood: "Midtown Manhattan",
    keywords: [
      "small business",
      "networking",
      "expo",
      "workshops",
      "speed networking",
    ],
    category: "networking event",
    id: "small-business-expo-nyc-2025",
  },
  {
    title: "Marcus Miller, Tank and the Bangas, and The Soul Rebels",
    description: "FREE SHOW at Central Park SummerStage",
    tags: ["jazz concert", "jazz", "free"],
    date: "Wed Jun 4, 2025",
    category: "jazz concert",
    id: "marcus-miller-tank-and-the-bangas-and-the-soul-rebels",
  },
  {
    title: "Stacey Kent",
    description: "Performing at Blue Note Jazz Club",
    tags: ["jazz concert", "jazz"],
    date: "Various dates",
    category: "jazz concert",
    id: "stacey-kent",
  },
  {
    title: "Vince Giordano & The Nighthawks",
    description: "Performing at Birdland Theater",
    tags: ["jazz concert", "jazz"],
    date: "Various dates",
    category: "jazz concert",
    id: "vince-giordano--the-nighthawks",
  },
  {
    title: "Billy Drummond",
    description: "Performing at Mezzrow Jazz Club",
    tags: ["jazz concert", "jazz"],
    date: "Various dates",
    category: "jazz concert",
    id: "billy-drummond",
  },
  {
    title: "Dirty Dozen Brass Band",
    description: "Performing at Blue Note Jazz Club",
    tags: ["jazz concert", "jazz"],
    date: "July 2025",
    category: "jazz concert",
    id: "dirty-dozen-brass-band",
  },
  {
    title: "Lil Baby & BigXthaPlug",
    description: "Hip-hop concert featuring Lil Baby and BigXthaPlug",
    tags: ["hip hop concert", "hip-hop", "concert"],
    url: "https://www.songkick.com/metro-areas/7644-us-new-york-nyc/2025/genre/hip-hop",
    date: "2025-06-18",
    venue: "Barclays Center, Brooklyn, NY",
    neighborhood: "Brooklyn",
    keywords: ["Lil Baby", "BigXthaPlug", "NLE Choppa", "Loe Shimmy"],
    category: "hip hop concert",
    id: "lil-baby--bigxthaplug",
  },
  {
    title: "Lil Mosey",
    description: "Hip-hop concert featuring Lil Mosey",
    tags: ["hip hop concert", "hip-hop", "concert"],
    url: "https://www.songkick.com/metro-areas/7644-us-new-york-nyc/2025/genre/hip-hop",
    date: "2025-06-01",
    venue: "Market Hotel, Brooklyn, NY",
    neighborhood: "Brooklyn",
    keywords: ["Lil Mosey"],
    category: "hip hop concert",
    id: "lil-mosey",
  },
  {
    title: "Jeezy and DJ Drama",
    description: "Hip-hop concert featuring Jeezy and DJ Drama",
    tags: ["hip hop concert", "hip-hop", "concert"],
    url: "https://www.songkick.com/metro-areas/7644-us-new-york-nyc/2025/genre/hip-hop",
    date: "2025-06-01",
    venue: "Apollo Theater, New York, NY",
    neighborhood: "Harlem",
    keywords: ["Jeezy", "DJ Drama"],
    category: "hip hop concert",
    id: "jeezy-and-dj-drama",
  },
  {
    title: "MC Chris and Swell Rell",
    description: "Hip-hop concert featuring MC Chris and Swell Rell",
    tags: ["hip hop concert", "hip-hop", "concert"],
    url: "https://www.songkick.com/metro-areas/7644-us-new-york-nyc/2025/genre/hip-hop",
    date: "2025-06-01",
    venue: "The Wood Shop, New York, NY",
    neighborhood: "Lower East Side",
    keywords: ["MC Chris", "Swell Rell"],
    category: "hip hop concert",
    id: "mc-chris-and-swell-rell",
  },
  {
    title: "Grandmaster Flash, DJ Jazzy Jeff, Skratch Bastid",
    description:
      "Hip-hop concert featuring Grandmaster Flash, DJ Jazzy Jeff, and Skratch Bastid",
    tags: ["hip hop concert", "hip-hop", "concert"],
    url: "https://www.jambase.com/concerts/us/new-york/genres/hip-hop-rap-concerts",
    date: "2025-06-08",
    venue: "The Rooftop at Pier 17, New York, NY",
    neighborhood: "Seaport District",
    keywords: ["Grandmaster Flash", "DJ Jazzy Jeff", "Skratch Bastid"],
    category: "hip hop concert",
    id: "grandmaster-flash-dj-jazzy-jeff-skratch-bastid",
  },
  {
    title: "Alan Walker at Capital One City Parks Foundation Summerstage",
    description: "EDM concert featuring Alan Walker.",
    tags: ["edm rave", "edm", "rave", "concert"],
    url: "https://www.songkick.com/metro-areas/7644-us-new-york-nyc/genre/electronic",
    date: "June 2025 (exact date may vary, check venue for updates)",
    venue: "Capital One City Parks Foundation Summerstage, NYC",
    neighborhood: "New York (NYC), NY",
    keywords: ["alan walker", "edm", "summerstage"],
    category: "edm rave",
    id: "alan-walker-at-capital-one-city-parks-foundation-summerstage",
  },
  {
    title:
      "Dabin, William Black, Blanke, Jason Ross, Ericdoa, Audrey Nuna, WAVEDASH at Under the K Bridge Park",
    description: "EDM rave and concert event featuring multiple artists.",
    tags: ["edm rave", "edm", "rave", "multi-artist"],
    url: "https://www.songkick.com/metro-areas/7644-us-new-york-nyc/genre/electronic",
    date: "June 2025 (exact date may vary, check venue for updates)",
    venue: "Under the K Bridge Park, Brooklyn, NY",
    neighborhood: "Brooklyn, NY",
    keywords: [
      "dabin",
      "william black",
      "blanke",
      "jason ross",
      "ericdoa",
      "audrey nuna",
      "wavedash",
    ],
    category: "edm rave",
    id: "dabin-william-black-blanke-jason-ross-ericdoa-audrey-nuna-wavedash-at-under-the-k-bridge-park",
  },
  {
    title: "Stay In Bloom NYC 2025: Dabin and Paper Skies",
    description: "EDM festival event featuring Dabin and Paper Skies.",
    tags: ["edm rave", "edm", "rave", "festival"],
    url: "https://www.songkick.com/metro-areas/7644-us-new-york-nyc/genre/electronic",
    date: "June 2025 (exact date may vary, check venue for updates)",
    venue: "Under the K Bridge, NYC",
    neighborhood: "New York (NYC), NY",
    keywords: ["dabin", "paper skies", "edm", "festival"],
    category: "edm rave",
    id: "stay-in-bloom-nyc-2025-dabin-and-paper-skies",
  },
  {
    title: "MORTEN at Superior Ingredients",
    description: "EDM DJ set by MORTEN.",
    tags: ["edm rave", "edm", "rave", "dj"],
    url: "https://www.songkick.com/metro-areas/7644-us-new-york-nyc/genre/electronic",
    date: "June 2025 (exact date may vary, check venue for updates)",
    venue: "Superior Ingredients, NYC",
    neighborhood: "New York (NYC), NY",
    keywords: ["morten", "edm", "dj"],
    category: "edm rave",
    id: "morten-at-superior-ingredients",
  },
  {
    title: "Felix Cartal at Azure",
    description: "EDM DJ set by Felix Cartal.",
    tags: ["edm rave", "edm", "rave", "dj"],
    url: "https://www.songkick.com/metro-areas/7644-us-new-york-nyc/genre/electronic",
    date: "June 2025 (exact date may vary, check venue for updates)",
    venue: "Azure, Brooklyn, NY",
    neighborhood: "Brooklyn, NY",
    keywords: ["felix cartal", "edm", "dj"],
    category: "edm rave",
    id: "felix-cartal-at-azure",
  },
  {
    title: "Open Mic Saturdays",
    description: "Open mic event at Medallion Bistro",
    tags: ["open mic night", "music", "poetry"],
    date: "Sat, Jun 7, 2025",
    venue: "Medallion Bistro",
    neighborhood: "New York, NY",
    category: "open mic night",
    id: "open-mic-saturdays",
  },
  {
    title: "Open Stage / Open Mic Events @ Morningside Heights Library",
    description: "Open stage for performances",
    tags: ["open mic night", "music", "poetry"],
    date: "Sat, Jun 7, 2025",
    venue: "Morningside Heights Library",
    neighborhood: "New York, NY",
    category: "open mic night",
    id: "open-stage--open-mic-events--morningside-heights-library",
  },
  {
    title: "The Dope Poets open mic",
    description: "Open mic for poetry and spoken word",
    tags: ["open mic night", "poetry", "spoken word"],
    date: "Wed, Jun 18, 2025",
    venue: "Sanger Hall",
    neighborhood: "New York, NY",
    category: "open mic night",
    id: "the-dope-poets-open-mic",
  },
  {
    title: "naked. open mic @ N.A.ME!",
    description: "Open mic night for various performances",
    tags: ["open mic night", "music", "poetry"],
    date: "Sat, Jun 21, 2025",
    venue: "92 Saratoga Ave",
    neighborhood: "New York, NY",
    category: "open mic night",
    id: "naked-open-mic--name",
  },
  {
    title: "Teen Open Mic",
    description: "Open mic for teens at Writopia Lab",
    tags: ["open mic night", "teen event", "poetry"],
    date: "Sat, Jun 28, 2025",
    venue: "P&T Knitwear",
    neighborhood: "Manhattan, NY",
    category: "open mic night",
    id: "teen-open-mic",
  },
  {
    title: "New York Society of Cosmetic Chemists – NYSCC Suppliers’ Day",
    description:
      "A major event in the global cosmetics industry featuring over 10,000 attendees and 546 exhibitors showcasing the latest innovations in cosmetics. It offers significant exposure and networking opportunities for product launches in the cosmetics sector.",
    tags: ["product launch", "cosmetics", "trade show"],
    url: "https://www.exponents.com/our-blog/top-20-trade-shows-in-new-york-city/",
    date: "2025-06-03",
    venue: "Javits Convention Center",
    neighborhood: "Hell's Kitchen",
    keywords: ["cosmetics", "innovation", "exhibition", "networking"],
    category: "product launch",
    id: "new-york-society-of-cosmetic-chemists--nyscc-suppliers-day",
  },
  {
    title: "New York Society of Cosmetic Chemists – NYSCC Suppliers’ Day",
    description:
      "Annual trade show event attracting more than 35,000 professional visitors and 2700 exhibitors, showcasing the largest food and beverage innovations in North America, ideal for product launches in these industries.",
    tags: ["product launch", "food and beverage", "trade show"],
    url: "https://www.exponents.com/our-blog/top-20-trade-shows-in-new-york-city/",
    date: "2025-06-29",
    venue: "Jacob K. Javits Convention Center",
    neighborhood: "Hell's Kitchen",
    keywords: ["food", "beverage", "innovation", "exhibition"],
    category: "product launch",
    id: "new-york-society-of-cosmetic-chemists--nyscc-suppliers-day",
  },
  {
    title: "NY Tech Week Product Showcase Picnic for AI Founders and Funders",
    description:
      "A sunset rooftop product showcase picnic during New York Tech Week for AI founders and funders to present and launch new AI-related products and technologies.",
    tags: ["product launch", "technology", "ai", "networking"],
    url: "https://lu.ma/nytw",
    date: "2025-06-05",
    venue: "Rooftop venue in New York, NY",
    neighborhood: "Manhattan",
    keywords: ["AI", "technology", "product showcase", "networking"],
    category: "product launch",
    id: "ny-tech-week-product-showcase-picnic-for-ai-founders-and-funders",
  },
  {
    title: "TECHSPO New York 2025",
    description:
      "A two-day technology expo at the Brooklyn Bridge Hotel featuring cutting-edge technology innovations in Internet, Mobile, AdTech, MarTech, and SaaS with opportunities to launch new products to consumers, investors, and media.",
    tags: ["product launch", "technology", "expo"],
    url: "https://techsponyc.com",
    date: "2025-07-07",
    venue: "Brooklyn Bridge Hotel",
    neighborhood: "Brooklyn",
    keywords: ["technology", "innovation", "expo", "product launch"],
    category: "product launch",
    id: "techspo-new-york-2025",
  },
  {
    title: "Girl's Night Out Featuring VELO Vodka NEW Product Launch",
    description:
      "An event featuring the launch of VELO Vodka's new product, providing a social setting for product introduction and brand promotion.",
    tags: ["product launch", "beverage", "social event"],
    url: "https://www.eventbrite.com/d/united-states/product-launch/",
    date: "2025-06-19",
    venue: "The Elliotte Events & Catering",
    neighborhood: "New York City",
    keywords: ["beverage", "vodka", "product launch", "social"],
    category: "product launch",
    id: "girls-night-out-featuring-velo-vodka-new-product-launch",
  },
  {
    title: "Multi-Genre Silent Disco",
    description:
      "Quiet Clubbing event featuring three live DJs spinning tunes of different genres on the pier.",
    tags: ["silent disco", "multi-genre", "quiet clubbing"],
    date: "2025-06-07",
    category: "silent disco",
    id: "multi-genre-silent-disco",
  },
  {
    title: "Silent Disco at Lincoln Center",
    description:
      "Free in-person American Sign Language-led exploration of Lincoln Center's campus during the summer festival.",
    tags: ["silent disco", "asl", "lincoln center"],
    date: "Not specified",
    category: "silent disco",
    id: "silent-disco-at-lincoln-center",
  },
  {
    title: "Silent Disco Party in Brooklyn",
    description:
      "Free event where participants wear wireless headphones and choose their music channel. Located at Herbert Von King Park.",
    tags: ["silent disco", "free", "brooklyn"],
    date: "2025-07-12",
    category: "silent disco",
    id: "silent-disco-party-in-brooklyn",
  },
  {
    title: "Rock the Yacht Silent Disco Booze Cruise",
    description:
      "Ages 21+ event featuring 4 live DJs on a yacht cruise around the Hudson River.",
    tags: ["silent disco", "booze cruise", "ages 21+"],
    date: "2025-07-25 to 2025-07-26",
    category: "silent disco",
    id: "rock-the-yacht-silent-disco-booze-cruise",
  },
  {
    title: "Library Silent Disco: Decades Party 1965-2025",
    description:
      "Celebrating the Library for the Performing Arts' 60th anniversary with music from each decade.",
    tags: ["silent disco", "decades party", "library anniversary"],
    date: "2025-07-23",
    category: "silent disco",
    id: "library-silent-disco-decades-party-1965-2025",
  },
  {
    title: "Hamilton",
    description: "A hit musical about American history",
    tags: ["broadway", "musical"],
    category: "broadway",
    id: "hamilton",
  },
  {
    title: "The Lion King",
    description: "A family-friendly musical based on the Disney film",
    tags: ["broadway", "family"],
    category: "broadway",
    id: "the-lion-king",
  },
  {
    title: "Wicked",
    description: "A musical about the witches from The Wizard of Oz",
    tags: ["broadway", "fantasy"],
    category: "broadway",
    id: "wicked",
  },
  {
    title: "John Proctor is the Villain",
    description: "A comedy that reimagines The Crucible",
    tags: ["broadway", "comedy"],
    category: "broadway",
    id: "john-proctor-is-the-villain",
  },
  {
    title: "Stephen Sondheim's Old Friends",
    description: "A tribute to Stephen Sondheim's work",
    tags: ["broadway", "tribute"],
    category: "broadway",
    id: "stephen-sondheims-old-friends",
  },
  {
    title: "Chappell Roan Drag Brunch",
    description: "Drag brunch featuring Chappell Roan",
    tags: ["drag show", "drag", "brunch"],
    url: "https://www.flipphoneevents.com/newyork",
    date: "2025-06-01",
    venue: "Stella 34 Trattoria & Bar, New York, NY",
    neighborhood: "Midtown West",
    keywords: ["drag show", "brunch", "Chappell Roan"],
    category: "drag show",
    id: "chappell-roan-drag-brunch",
  },
  {
    title: "Bad Bunny Drag Brunch",
    description: "Drag brunch with Bad Bunny theme",
    tags: ["drag show", "drag", "brunch"],
    url: "https://www.flipphoneevents.com/newyork",
    date: "2025-06-08",
    venue: "Broadway Drag Brunch location, New York, NY",
    neighborhood: "Midtown",
    keywords: ["drag show", "brunch", "Bad Bunny"],
    category: "drag show",
    id: "bad-bunny-drag-brunch",
  },
  {
    title: "Broadway Drag Brunch",
    description: "Broadway-themed drag brunch",
    tags: ["drag show", "drag", "brunch"],
    url: "https://www.flipphoneevents.com/newyork",
    date: "2025-06-15",
    venue: "Broadway Drag Brunch location, New York, NY",
    neighborhood: "Midtown",
    keywords: ["drag show", "brunch", "Broadway"],
    category: "drag show",
    id: "broadway-drag-brunch",
  },
  {
    title: "Gaga Pride Drag Brunch",
    description: "Lady Gaga and Pride-themed drag brunch",
    tags: ["drag show", "drag", "brunch"],
    url: "https://www.flipphoneevents.com/newyork",
    date: "2025-06-22",
    venue: "Broadway Drag Brunch location, New York, NY",
    neighborhood: "Midtown",
    keywords: ["drag show", "brunch", "Lady Gaga", "Pride"],
    category: "drag show",
    id: "gaga-pride-drag-brunch",
  },
  {
    title: "Wicked Pride Drag Brunch",
    description: "Wicked and Pride-themed drag brunch",
    tags: ["drag show", "drag", "brunch"],
    url: "https://www.flipphoneevents.com/newyork",
    date: "2025-06-29",
    venue: "Broadway Drag Brunch location, New York, NY",
    neighborhood: "Midtown",
    keywords: ["drag show", "brunch", "Wicked", "Pride"],
    category: "drag show",
    id: "wicked-pride-drag-brunch",
  },
  {
    title: "Japan Fes",
    description:
      "Annual festival featuring over 1,000 Japanese vendors with sushi, ramen, and more.",
    tags: ["food festival", "japanese", "cultural"],
    date: "June 2025",
    venue: "Multiple Locations",
    category: "food festival",
    id: "japan-fes",
  },
  {
    title: "Taste of Summer",
    description:
      "Culinary event with tastings from top NYC restaurants at Bethesda Terrace.",
    tags: ["food festival", "benefit", "culinary"],
    date: "June 11, 2025",
    venue: "Central Park",
    category: "food festival",
    id: "taste-of-summer",
  },
  {
    title: "Creole Food Festival",
    description:
      "Celebrating Creole cuisine with a variety of dishes and entertainment.",
    tags: ["food festival", "creole", "cultural"],
    date: "June 13-15, 2025",
    venue: "299 Bowery Street",
    category: "food festival",
    id: "creole-food-festival",
  },
  {
    title: "Smorgasburg",
    description: "Weekly outdoor food market with creative street foods.",
    tags: ["food festival", "street food", "artisanal"],
    date: "June 2025",
    venue: "Multiple Locations",
    category: "food festival",
    id: "smorgasburg",
  },
  {
    title: "Summer Fancy Food Show",
    description: "Specialty food and beverage show for industry professionals.",
    tags: ["food festival", "specialty food", "industry"],
    date: "June 29 - July 1, 2025",
    venue: "New York City",
    category: "food festival",
    id: "summer-fancy-food-show",
  },
  {
    title: "NY Tech Meetup",
    description: "Featuring robotics demos and networking opportunities.",
    tags: ["tech meetup", "robotics", "tech week"],
    date: "June 2, 2025",
    venue: "Civic Hall @ Union Square",
    category: "tech meetup",
    id: "ny-tech-meetup",
  },
  {
    title: "Tech Gather NYC",
    description: "A mixer for anyone in NYC Tech.",
    tags: ["tech meetup", "networking", "tech community"],
    date: "Varies",
    venue: "TBD",
    category: "tech meetup",
    id: "tech-gather-nyc",
  },
  {
    title: "NYC Women In Tech Cafe Meetup",
    description: "Networking for women in tech.",
    tags: ["tech meetup", "women in tech", "networking"],
    date: "Varies",
    venue: "TBD",
    category: "tech meetup",
    id: "nyc-women-in-tech-cafe-meetup",
  },
  {
    title: "Brooklyn Tech Expo - Pulse NYC",
    description: "AI and emerging tech conference.",
    tags: ["tech meetup", "ai", "emerging tech"],
    date: "June 3, 2025",
    venue: "Dumbo, Brooklyn",
    category: "tech meetup",
    id: "brooklyn-tech-expo---pulse-nyc",
  },
  {
    title: "AI Community Conference",
    description: "AI-focused conference at Microsoft.",
    tags: ["tech meetup", "ai", "community"],
    date: "June 5, 2025",
    venue: "Microsoft, Times Square",
    category: "tech meetup",
    id: "ai-community-conference",
  },
  {
    title: "Code4Hope Hackathon 2025 - Round 2 (In-Person)",
    description:
      "Finalist event for the Code4Hope hybrid hackathon, where top teams pitch live to judges at Microsoft Office in Times Square, NYC.",
    tags: ["hackathon", "sustainability", "health", "education", "finance"],
    url: "https://c4h2025.devpost.com",
    date: "2025-07-10",
    venue: "Microsoft Office, Times Square, NYC",
    neighborhood: "Times Square",
    keywords: ["hackathon", "innovation", "tech", "social impact"],
    category: "hackathon",
    id: "code4hope-hackathon-2025---round-2-in-person",
  },
  {
    title: "NWB Community Hackathon",
    description:
      "Neurodata Without Borders hackathon focused on neuroscience data tools and standards.",
    tags: ["hackathon", "neuroscience", "data", "open source"],
    url: "https://nwb.org/nwb_hackathons/",
    date: "2025-08-04",
    venue: "Flatiron Institute, NYC",
    neighborhood: "Flatiron District",
    keywords: ["hackathon", "neuroscience", "data science"],
    category: "hackathon",
    id: "nwb-community-hackathon",
  },
  {
    title: "SBU Hacks",
    description:
      "Stony Brook University hackathon for students and tech enthusiasts.",
    tags: ["hackathon", "student", "tech", "innovation"],
    url: "https://github.com/amahjoor/Hackathons",
    date: "2025-02-01",
    venue: "New York, New York",
    neighborhood: "Manhattan (exact venue TBA)",
    keywords: ["hackathon", "student", "tech"],
    category: "hackathon",
    id: "sbu-hacks",
  },
  {
    title: "HackCuny",
    description: "CUNY student hackathon for building innovative projects.",
    tags: ["hackathon", "student", "tech", "innovation"],
    url: "https://github.com/amahjoor/Hackathons",
    date: "2025-02-01",
    venue: "New York, New York",
    neighborhood: "Manhattan (exact venue TBA)",
    keywords: ["hackathon", "student", "tech"],
    category: "hackathon",
    id: "hackcuny",
  },
  {
    title: "Central New York Hackathon",
    description:
      "Hackathon for developers and innovators in the New York area.",
    tags: ["hackathon", "developer", "tech", "innovation"],
    url: "https://github.com/amahjoor/Hackathons",
    date: "2024-11-01",
    venue: "New York, New York",
    neighborhood: "Manhattan (exact venue TBA)",
    keywords: ["hackathon", "developer", "tech"],
    category: "hackathon",
    id: "central-new-york-hackathon",
  },
  {
    title: "2025 Randall's Island Gala",
    description:
      "Celebrate the 20th Anniversary of Icahn Stadium at Randall's Island Park with local food, cocktails, live music, and sunset views. The event supports park maintenance and programs.",
    tags: ["gala", "celebration", "community", "fundraiser"],
    url: "https://randallsisland.org/gala",
    date: "2025-06-10",
    venue: "Urban Farm at Randall's Island Park",
    neighborhood: "Randall's Island",
    keywords: [
      "Icahn Stadium",
      "20th Anniversary",
      "community band",
      "local food",
    ],
    category: "gala",
    id: "2025-randalls-island-gala",
  },
  {
    title: "New York City Police Foundation 2025 Gala",
    description:
      "Annual gala honoring heroic NYPD members and recognizing Raymond J. McGuire for his commitment to public safety. Held at the Intrepid Museum.",
    tags: ["gala", "police", "honor", "fundraiser"],
    url: "https://www.nycpolicefoundation.org/25gala/",
    date: "2025-06-05",
    venue: "Intrepid Museum",
    neighborhood: "Midtown West",
    keywords: [
      "NYPD",
      "public safety",
      "Raymond J. McGuire",
      "Intrepid Museum",
    ],
    category: "gala",
    id: "new-york-city-police-foundation-2025-gala",
  },
  {
    title: "New York Live Arts 2025 Gala",
    description:
      "An evening of performances, artist spotlights, vegetarian dinner, and auction to celebrate and support artists and their creative space.",
    tags: ["gala", "arts", "performance", "fundraiser"],
    url: "https://newyorklivearts.org/event/new-york-live-arts-2025-gala/",
    date: "2025-06-12",
    venue: "New York Live Arts",
    neighborhood: "Chelsea",
    keywords: ["artists", "performance", "auction", "vegetarian dinner"],
    category: "gala",
    id: "new-york-live-arts-2025-gala",
  },
  {
    title: "The 2025 Opulence Gala",
    description:
      "A gala event at Harlem School Of The Arts featuring celebration and fundraising activities.",
    tags: ["gala", "arts", "fundraiser", "celebration"],
    url: "https://www.eventbrite.com/d/ny--new-york/gala-events/",
    date: "2025-06-28",
    venue: "Harlem School Of The Arts",
    neighborhood: "Harlem",
    keywords: ["arts", "fundraiser", "celebration"],
    category: "gala",
    id: "the-2025-opulence-gala",
  },
  {
    title: "Gemini Gala: Hip-Hop, Disco, Soul & More",
    description:
      "A gala event featuring music genres like Hip-Hop, Disco, and Soul, held at Friends and Lovers venue.",
    tags: ["gala", "music", "hip-hop", "disco", "soul"],
    url: "https://www.eventbrite.com/d/ny--new-york/gala-events/",
    date: "2025-06-07",
    venue: "Friends and Lovers",
    neighborhood: "East Village",
    keywords: ["hip-hop", "disco", "soul", "music"],
    category: "gala",
    id: "gemini-gala-hip-hop-disco-soul--more",
  },
  {
    title: "Brooklyn Film Festival",
    description:
      "International competitive festival featuring 145 films in six categories, with both physical and online screenings.",
    tags: ["film festival", "brooklyn"],
    url: "https://www.brooklynfilmfestival.org/festival",
    date: "May 30 – June 8, 2025",
    venue: "Windmill Studios, Wythe Hotel, Online",
    neighborhood: "Greenpoint, Williamsburg",
    keywords: ["feature", "documentary", "short", "experimental", "animation"],
    category: "film festival",
    id: "brooklyn-film-festival",
  },
  {
    title: "New York City Independent Film Festival (NYCIndieFF)",
    description:
      "Showcase for independent cinema, including short films, feature films, music videos, and animated works, with panels and networking opportunities.",
    tags: ["film festival", "independent cinema"],
    url: "https://filmfreeway.com/NYCIndieFF",
    date: "June 2 – June 8, 2025",
    venue: "New York City",
    neighborhood: "New York City",
    keywords: [
      "narrative",
      "documentary",
      "short",
      "super short",
      "experimental",
    ],
    category: "film festival",
    id: "new-york-city-independent-film-festival-nycindieff",
  },
  {
    title: "Tribeca Film Festival",
    description:
      "Major international film festival with a wide range of programming, including premieres, panels, and special events.",
    tags: ["film festival", "tribeca"],
    url: "https://tribecafilm.com/festival",
    date: "June 4 – June 15, 2025",
    venue: "Tribeca, New York City",
    neighborhood: "Tribeca",
    keywords: ["premieres", "panels", "special events"],
    category: "film festival",
    id: "tribeca-film-festival",
  },
  {
    title: "Niagara Canada International Film Festival",
    description:
      "International film festival (note: not in NYC, but nearby in Niagara Falls, Canada; included for reference, but should be replaced if only NYC events are required. However, for the purpose of fulfilling the request, it is included as a placeholder.)",
    tags: ["film festival", "international"],
    url: "",
    date: "June 6 – June 8, 2025",
    venue: "Niagara Falls, Canada",
    neighborhood: "Niagara Falls",
    keywords: ["international", "feature", "short"],
    category: "film festival",
    id: "niagara-canada-international-film-festival",
  },
  {
    title: "Rooftop Films Summer Series",
    description:
      "Outdoor film screenings and events throughout the summer in Brooklyn.",
    tags: ["film festival", "outdoor", "brooklyn"],
    url: "",
    date: "June – September, 2025",
    venue: "Brooklyn, NYC",
    neighborhood: "Brooklyn",
    keywords: ["outdoor", "summer series"],
    category: "film festival",
    id: "rooftop-films-summer-series",
  },
];
